server:
  port: 8500
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: happyride
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DOCKER_HOST_IP:localhost}:8431/happyride-passenger
    username: postgres
    password: postgres
  flyway:
    schemas:
      - happyride