repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
releases:
  - name: postgresql-address
    namespace: {{ env "NAMESPACE" | default "happyride" }} 
    chart: bitnami/postgresql
    version: 8.10.13   
    wait: false
    values:
      - ../postgresql-config.yaml
      - config.yaml
  - name: address-service-common
    namespace: {{ env "NAMESPACE" | default "happyride" }}     
    chart: charts/address-service-common   
  # - name: address-service-v1-0
  #   namespace: {{ env "NAMESPACE" | default "happyride" }}     
  #   chart: charts/address-service
  #   values:
  #     - config.yaml
  #     - address-service-config.yaml
  #     - serviceVersion: "1"
  #       appVersion: "1.0.0"  
  - name: address-service-v1-1
    namespace: {{ env "NAMESPACE" | default "happyride" }}     
    chart: charts/address-service
    values:
      - config.yaml
      - address-service-config.yaml
      - serviceVersion: "2"
        appVersion: {{ requiredEnv "ADDRESS_SERVICE_VERSION" | quote }}   
        image:
          repository: {{ printf "%s/happyride/happyride-address-service" (requiredEnv "CONTAINER_REGISTRY") | quote }}  